AppName: go-pos
#appEnv: test
AppEnv: production

HttpUrl: 127.0.0.1
HttpPort: 8080
HttpAllowedOrigins: "*"
Loglevel: debug

DBConnection: postgres
DBHost: localhost
DBPort: 5432
DBdatabase: templatedatabase
#DBdatabase: testdb
DBUsername: postgres
DBPassword: secret


RedisServer: localhost:6379
RedisPassword: 

TokenSymmetricKey: 12345678901234567890123456789012
TokenDuration: 15m
ShutDownTime: 1s
ShutDowntype: 

MaxConns: 10
MinConns: 3
MaxConnLifetime: 10
MaxConnIdleTime: 3
